version: '3.8'

services:
  web:
    build:
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - FIRE_BASE_API=${FIRE_BASE_API}
        - FR_AUTHDOMAIN=${FR_AUTHDOMAIN}
        - FR_APP_ID=${FR_APP_ID}
    ports:
      - "3000:3000"
      # Development için gerekli port
      - "5555:5555"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FIRE_BASE_API=${FIRE_BASE_API}
      - FR_AUTHDOMAIN=${FR_AUTHDOMAIN}
      - FR_APP_ID=${FR_APP_ID}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: always 